name: CD - Publish to NPM

on:
  push:
    branches:
      - main # Ne se déclenche que sur la branche main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Publish Packages
        run: |
          # On boucle sur chaque dossier dans packages/
          for dir in src/packages/*; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              cd $dir
              # On tente de publier. 
              # Si la version existe déjà sur NPM, la commande échouera, 
              # donc on ajoute || true pour passer au package suivant.
              npm publish --access public || echo "Skip: Version already published for $(basename $dir)"
              cd - > /dev/null
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
